// extension/src/previewEntry.ts
import * as path from 'node:path';

export interface PreviewTarget {
  /** Absolute path to the file containing the widget to preview. */
  targetFilePath: string;
  /** Absolute path where the generated entrypoint file will be written. */
  entryFilePath: string;
  /** Symbol to preview, as found by findPreviewSites. */
  symbolName: string;
  kind: 'class' | 'function' | 'getter';
  /**
   * Injected into the file header on each hot-reload rewrite so the file's
   * content (and mtime) changes every save. flutter's incremental compiler
   * only rescans imports of files it detects as changed; without this the
   * entrypoint looks identical and the compiler sends an empty delta, leaving
   * the running widget unchanged even though the user's source file is newer.
   */
  stamp?: string;
}

function referenceFor(target: PreviewTarget): string {
  return target.kind === 'getter' ? target.symbolName : `${target.symbolName}()`;
}

/**
 * Generates the `main.dart` source for a preview run: imports the target
 * file, wraps the chosen widget in a minimal MaterialApp+Scaffold, and hands
 * it to `previewCapture` (from the live_test_view package) to boot and
 * stream frames from.
 */
export function generatePreviewEntry(target: PreviewTarget): string {
  const relImport = path
    .relative(path.dirname(target.entryFilePath), target.targetFilePath)
    .split(path.sep)
    .join('/');
  const header = target.stamp
    ? `// Generated by live-test-view — reload ${target.stamp}. Do not edit or commit.`
    : `// Generated by live-test-view — initial launch. Do not edit or commit.`;
  return `${header}
import 'package:flutter/material.dart';
import 'package:live_test_view/live_test_view.dart';

import '${relImport}';

void main() {
  previewCapture(() => MaterialApp(home: Scaffold(body: Builder(builder: (_) => ${referenceFor(target)}))));
}
`;
}
