// extension/src/previewEntry.ts
import * as path from 'node:path';

export interface PreviewTarget {
  /** Absolute path to the file containing the widget to preview. */
  targetFilePath: string;
  /**
   * Absolute path where the generated entrypoint file will be written. Must
   * live inside the target package's `lib/` directory — see
   * `previewEntryPathFor` for why hot reload depends on that.
   */
  entryFilePath: string;
  /** Symbol to preview, as found by findPreviewSites. */
  symbolName: string;
  kind: 'class' | 'function' | 'getter';
}

function referenceFor(target: PreviewTarget): string {
  return target.kind === 'getter' ? target.symbolName : `${target.symbolName}()`;
}

/** Basename of the generated entrypoint. Leading dot keeps it out of
 * `dart analyze`/`flutter analyze` (the analyzer skips dot-prefixed
 * resources) and out of most `git status` noise, even though it has to sit
 * inside `lib/`. */
export const PREVIEW_ENTRY_BASENAME = '.live_test_view_preview_entry.dart';

/**
 * Where the generated entrypoint must be written, given a package root (the
 * directory holding `pubspec.yaml`).
 *
 * It has to be inside `lib/`, and that is load-bearing for hot reload, not a
 * stylistic choice. `flutter run` resolves an entrypoint under `lib/` to its
 * `package:` URI, and the CFE then resolves that library's *relative*
 * imports against that `package:` URI too — so the previewed widget's
 * library is keyed as `package:<pkg>/<path>.dart` in the incremental
 * compiler. On hot reload, flutter_tools converts every invalidated file
 * path that falls inside some package's `lib/` into that package's
 * `package:` URI before handing the invalidation list to the CFE
 * (`flutter_tools/lib/src/compile.dart`, `_compile`/`recompile`). Those two
 * URIs only agree when the entrypoint itself is under `lib/`.
 *
 * With the entrypoint outside `lib/` (it used to live in
 * `.dart_tool/live_test_view/`) the entrypoint keeps a `file:///` URI, its
 * relative import gives the target library a `file:///` URI too, and the
 * `package:` URI flutter_tools sends on reload matches no library the CFE
 * knows. The CFE invalidates nothing, emits an empty delta, and the VM
 * reports `Reloaded 0 of N libraries` — the widget keeps running old code
 * while frames keep flowing, which looks exactly like "hot reload silently
 * does nothing".
 */
export function previewEntryPathFor(projectRoot: string): string {
  return path.join(projectRoot, 'lib', PREVIEW_ENTRY_BASENAME);
}

/**
 * Generates the `main.dart` source for a preview run: imports the target
 * file, wraps the chosen widget in a minimal MaterialApp+Scaffold, and hands
 * it to `previewCapture` (from the live_test_view package) to boot and
 * stream frames from.
 */
export function generatePreviewEntry(target: PreviewTarget): string {
  const relImport = path
    .relative(path.dirname(target.entryFilePath), target.targetFilePath)
    .split(path.sep)
    .join('/');
  return `// Generated by live-test-view. Do not edit or commit; deleted when the preview stops.
import 'package:flutter/material.dart';
import 'package:live_test_view/live_test_view.dart';

import '${relImport}';

void main() {
  previewCapture(() => MaterialApp(home: Scaffold(body: Builder(builder: (_) => ${referenceFor(target)}))));
}
`;
}
