import 'dart:io';

const configTemplate = '''
// Generated by live_test_view (https://pub.dev/packages/live_test_view).
// Streams rendered frames to the Live Test View editor extension when the
// extension runs a test. A strict no-op under plain `flutter test`.
import 'dart:async';

import 'package:live_test_view/live_test_view.dart';

Future<void> testExecutable(FutureOr<void> Function() testMain) =>
    liveTestView(testMain);
''';

sealed class InstallResult {
  const InstallResult();
}

class Installed extends InstallResult {
  const Installed();
}

class NoTestDirectory extends InstallResult {
  const NoTestDirectory();
}

class ConfigAlreadyExists extends InstallResult {
  const ConfigAlreadyExists();
}

InstallResult install(Directory projectRoot) {
  final testDir = Directory('${projectRoot.path}/test');
  if (!testDir.existsSync()) return const NoTestDirectory();
  final config = File('${testDir.path}/flutter_test_config.dart');
  if (config.existsSync()) return const ConfigAlreadyExists();
  config.writeAsStringSync(configTemplate);
  return const Installed();
}
